export const ACTION_SETUSER = 'SETUSER';
export const ACTION_RETRIVE_USER = 'RETRIVE_USER';
export const ACTION_LOGOUT = 'LOGOUT';

export const ACTION_USER_IMAGE_CHANGE = 'ACTION_USER_IMAGE_CHANGE';
export const ACTION_SET_USER_LOCATION = 'ACTION_SET_USER_LOCATION';
